apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-aspnet-app
  # Assumendo che deployi in pcto-group-c tramite Portainer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-aspnet-app
  template:
    metadata:
      labels:
        app: my-aspnet-app
    spec:
      containers:
      - name: my-aspnet-app-container
        # !!! RICORDATI DI CAMBIARE QUESTA IMMAGINE !!!
        image: your-registry/your-aspnet-app:latest
        ports:
        - containerPort: 80
        # --- INIZIO BLOCCO AGGIUNTO ---
        resources:
          requests:
            memory: "64Mi"   # Esempio: Richiede almeno 64 Mebibytes di RAM
            cpu: "100m"     # Esempio: Richiede almeno 0.1 core di CPU (100 millicores)
          limits:
            memory: "256Mi"  # Esempio: Limite massimo di 256 Mebibytes di RAM
            cpu: "500m"     # Esempio: Limite massimo di 0.5 core di CPU (500 millicores)
        # --- FINE BLOCCO AGGIUNTO ---
---
apiVersion: v1
kind: Service
metadata:
  name: my-aspnet-service
  # Assumendo che deployi in pcto-group-c tramite Portainer
spec:
  selector:
    app: my-aspnet-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
