apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-aspnet-app
  # Nessun namespace specificato qui, userà 'pcto-group-c' da Portainer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-aspnet-app
  template:
    metadata:
      labels:
        app: my-aspnet-app
    spec:
      containers:
      - name: my-aspnet-app-container
        # !!! RICORDATI DI CAMBIARE QUESTA IMMAGINE !!!
        image: your-registry/your-aspnet-app:latest
        ports:
        - containerPort: 80 # Porta interna della tua app ASP.NET
---
apiVersion: v1
kind: Service
metadata:
  name: my-aspnet-service
  # Nessun namespace specificato qui, userà 'pcto-group-c' da Portainer
spec:
  selector:
    app: my-aspnet-app # Deve corrispondere alle labels del template del Deployment
  ports:
    - protocol: TCP
      port: 80 # Porta su cui il servizio ascolta all'interno del cluster
      targetPort: 80 # Porta del container (deve corrispondere a containerPort sopra)
  type: ClusterIP
